version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

default_matrix: &default_matrix
  e:
    name: php/php
    php-version: <<matrix.php-version>>
  matrix:
    parameters:
      php-version: [ "8.2", "8.3", "8.4" ]

workflows:
  version: 2
  full:
    jobs:
      - php/phpunit-tests:
          <<: *default_matrix
          pecl_extensions: "pcov"
          context: "GCR + Artifact Bucket Access"
      - php/static-analysis:
          <<: *default_matrix
          generate_ide_helper: false
